name: Build Fritzing MSI Installer

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout fritzing-app
        uses: actions/checkout@v4
        with:
          path: fritzing-app
          submodules: recursive

      - name: Checkout fritzing-parts (Pustaka Komponen)
        uses: actions/checkout@v4
        with:
          repository: fritzing/fritzing-parts
          path: fritzing-parts

      - name: Checkout libgit2
        uses: actions/checkout@v4
        with:
          repository: libgit2/libgit2
          ref: v1.7.2
          path: libgit2

      # Mengunduh & Mengekstrak Boost 1.81.0 (Versi Kompatibel Fritzing)
      - name: Download & Extract Boost 1.81.0
        run: |
          curl.exe -sL "https://archives.boost.io/release/1.81.0/source/boost_1_81_0.zip" -o "boost.zip"
          tar.exe -xf boost.zip

      - name: Install Qt Framework
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: 'true'

      - name: Setup MSVC Compiler Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build libgit2
        run: |
          cd libgit2
          mkdir build64
          cd build64
          cmake .. -G "Visual Studio 17 2022" -A x64 -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF
          cmake --build . --config Release

      - name: Run QMake and Compile Fritzing
        run: |
          cd fritzing-app
          qmake phoenix.pro "CONFIG+=release" "boost_root=D:/a/fritzing-app/fritzing-app/boost_1_81_0"
          nmake

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fritzing-Executable-Build
          path: fritzing-app/release/
