name: Build Fritzing MSI Installer

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout fritzing-app
        uses: actions/checkout@v4
        with:
          path: fritzing-app
          submodules: recursive

      - name: Checkout fritzing-parts (Library Komponen)
        uses: actions/checkout@v4
        with:
          repository: fritzing/fritzing-parts
          path: fritzing-parts

      - name: Install Pustaka Dependensi (Boost & Libgit2)
        run: |
          vcpkg install libgit2:x64-windows boost-property-tree:x64-windows boost-spirit:x64-windows quazip:x64-windows

      - name: Install Qt Framework
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          cache: 'true'

      - name: Setup MSVC Compiler Environment
        uses: ilammy/msvc-dev-cmd@v1

      # Menggunakan qmake & nmake standar Qt (Bukan CMake)
      - name: Run QMake and Compile Fritzing
        run: |
          cd fritzing-app
          qmake phoenix.pro "CONFIG+=release"
          nmake

      # Mengunggah hasil kompilasi executable Fritzing
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fritzing-Executable-Build
          path: fritzing-app/release/
